### ISSUE TITLE
Error in running the given example

### ISSUE THREAD

**Issue by vishal-h** [ananthakumaran/barlix#6]
Version used is 0.4.0

 Barlix.Code39.encode!("BARLIX") |> Barlix.PNG.print()
** (UndefinedFunctionError) function Barlix.PNG.print/1 is undefined or private. Did you mean one of:

      * print/2

    (barlix) Barlix.PNG.print({:D1, [1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, ...]})

**Comment by ananthakumaran** [comment]
Not sure why you get error, this is what I get on 0.5.0
```
iex(1)> Barlix.Code39.encode!("BARLIX") |> Barlix.PNG.print()
{:ok,
 [
   [
     [
       [
         [[], <<137, 80, 78, 71, 13, 10, 26, 10>>],
         <<0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 123, 0, 0, 0, 120, 8, 0, 0, 0,
           0, 247, 56, 210, 13>>
       ],
       [<<0, 0, 0, 2, 73, 68, 65, 84, 120, 156, 98, 164, 145, 43>>]
     ],
     [
       <<0, 0, 0, 102, 73, 68, 65, 84, 237, 205, 75, 10, 0, 32, 8, 5, 64, 239,
         127, 233, 34, 10, 250, 173, 43, 130, 121, 184, 144, 212, 38, 210, 187,
         4, 155, 205, 102, 159, 181, 163, 84, 212, 106, 221, ...>>
     ]
   ],
   <<0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130>>
 ]}
```

**Comment by vishal-h** [comment]
setting the version to 0.5.0 in mix.exs results in error ({:barlix, "~> 0.5.0"})

an exception was raised:
    ** (UndefinedFunctionError) function :badarg.exception/1 is undefined (module :badarg is not available)
        :badarg.exception([])
        (hex) lib/hex/registry/server.ex:33: Hex.Registry.Server.open/1
        (hex) lib/hex/remote_converger.ex:18: Hex.RemoteConverger.converge/2
        (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
        (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
        (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
        (mix) lib/mix/tasks/deps.get.ex:28: Mix.Tasks.Deps.Get.run/1
        (mix) lib/mix/task.ex:316: Mix.Task.run_task/3ElixirLS

The releases section in the repo is up to 0.4.0. Anything to do with that?

**Comment by vishal-h** [comment]
Elixir version where this is being tested is

Erlang/OTP 20 [erts-9.3] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10]

Elixir 1.7.1 (compiled with Erlang/OTP 19)

**Comment by vishal-h** [comment]
Followed the suggestion on https://elixirforum.com/t/mix-deps-get-is-failing-due-to-genserver-hex-registry-server-terminating/22993/3

```rm -rf ~/.hex followed by mix deps.get```

**Comment by ananthakumaran** [comment]
> Erlang/OTP 20 [erts-9.3] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10]

> Elixir 1.7.1 (compiled with Erlang/OTP 19)

Looks like you are running elixir compiled with otp-19 on otp-20. Make sure the otp versions are same.
