### ISSUE TITLE
Support for DataURL

### ISSUE THREAD

**Issue by vishal-h** [ananthakumaran/barlix#7]
something like Barlix.Code39.encode!("123") |> Barlix.DataUrl should produce

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAB4CAYAAABb59j9AAAABmJLR0QA/wD/AP+gvaeTAAABkUlEQVR4nO3ZOwrDMBQAQSnk/ldWqjSGgH/BsMx0RgI/m0WN5lprDYh4PT0A3EnQpAiaFEGTImhSBE2KoEkRNCmCJuW9d+Occ4wxxq+Lxe3693nr6PrZ/Xvn+9c8/3r/2fWz81z9v1e/5+hFthOaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhSBE2KoEkRNCmCJkXQpAiaFEGTImhS5lprPT0E3MUJTYqgSRE0KYImRdCkCJoUQZMiaFIETcoH+81T6dyoQnYAAAAASUVORK5CYII=

**Comment by vishal-h** [comment]
Functionality is similar to npm/canvas.toDataURL("image/png");

**Comment by ananthakumaran** [comment]
I will look into more details later. We recently merged a PR https://github.com/ananthakumaran/barlix/pull/5/files which added ability to return raw png binary. You could probably run it through base64 encoder to generate the above url

**Comment by vishal-h** [comment]
This should do the trick

{:ok, code} = Barlix.Code39.encode!("123") |> Barlix.PNG.print()
code |> IO.iodata_to_binary |> Base.encode64

which yields
"iVBORw0KGgoAAAANSUhEUgAAAFQAAAB4CAAAAABJbopQAAAAAklEQVR4nGKkkSsAAABQSURBVO3MMQoAIAwDwPz/0xURRHcdxCulJEMvdWEChUJ7TGXsODVTlrK0/QcKhUKhUCgUCoVCoVAoFAqFQqFQKBQKhUKhUCj0QfTcQKHfog0SdJvEiV0vdgAAAABJRU5ErkJggg=="

It would help to have a ```print!``` method so that it can be piped. Like
Barlix.Code39.encode!("123") |> Barlix.PNG.print! |> IO.iodata_to_binary |> Base.encode64

**Comment by vishal-h** [comment]
Barlix.Code39.data_url("123") would do 
"data:image/png;base64," <> (Barlix.Code39.encode!("123") |> Barlix.PNG.print! |> IO.iodata_to_binary |> Base.encode64)
to yield the dataUrl

**Comment by ananthakumaran** [comment]
I am going to close this issue for now. Generating base64 url is not a direct concern of this library and given that it's quite easy to do with the available api, I am not interested in expanding the barlix api.
